### ISSUE TITLE
[建议]邮件过多

### ISSUE THREAD

**Issue by fantastlcok** [thundernet8/Tint-Pro#12]
一次订单交易多达5份邮件，实在太多了。如果每天50单交易，则多大250封邮件需要发送。
一封管理员通知邮件
一封免签支付宝通知邮件
一封用户通知邮件
一封用户订单变更邮件
一封用户商品付费内容邮件
本来打算自己改改，但是似乎邮件发送代码被加密了，没能找到。
因为我使用的是收费邮件推送服务，希望能少一些。希望能告诉我如何修改，以上内容无需邮件通知。
新用户注册也会发送管理员通知邮件，我通过wp钩子似乎也无法关闭。

**Comment by thundernet8** [comment]
已经在后台邮件通知相关选项区添加了订单事件的通知开关，默认开启，可以关闭以减少邮件发送量
