### ISSUE TITLE
[BUG]注册页面css样式错误

### ISSUE THREAD

**Issue by fantastlcok** [thundernet8/Tint-Pro#14]
地址：https://webapproach.net/m/signup?redirect_to=https%3A%2F%2Fwebapproach.net
详细代码
`.action-page.signup>.wrapper>.main {
    top: 50%;
    margin-top: -300px;
}`

**Comment by thundernet8** [comment]
在什么样的设备和屏幕尺寸下，现在我只做了PC 1120px以上保证无问题，响应式未涉及

**Comment by fantastlcok** [comment]
@thundernet8 1366x768
