### ISSUE TITLE
新版主题问题反馈

### ISSUE THREAD

**Issue by fantastlcok** [thundernet8/Tint-Pro#2]
**问题：**

1. 主题商城固定链接问题（具体表现商城首页进不去，商品页面可以。）。。
2. 订单支付页面二维码 未标注是支付宝还是微信 。
3. IOS支付宝扫码转账无备注选项。
4. 免签需要的支付宝cookie通过js无法导出完全，需要直接查看网页header头复制完整cookie。
5. 登出登录错误。网站使用https 登出被引导到https://域名:80，手机登录也存在此问题。

**建议：**

1. 希望能告主题使用的字体图标能在哪里看到图标列表？方便设置菜单图标，没能搜索到。
2. 希望商品页面商品能显示剩余数量。
3. 希望能告知邮件发送代码在哪，想取消掉一些邮件发送。(一笔订单4封邮件太多了)
4. 微信支付需要手动确认，还需要添加好友。建议移除微信二维码。

**Comment by thundernet8** [comment]
问题1 你的WP固定链接模式请给出
问题2 已增加标注
问题3 转账只有放账户二维码才行，这时扫出来是个人资料界面，有加好友和转账两个按钮，但是部分人未知原因无法进入该界面
问题4 请看教程，在chrome的Console里面可以打印出来，复制
问题5 暂时未知，但是看你页面内容http/https混合，可能影响判断

**Comment by thundernet8** [comment]
建议1：
主题图标是在IconMoon自定义选择的，预览见https://webapproach.net/tint/tico/demo.html

**Comment by thundernet8** [comment]
建议2：
建议3：
建议4：

稍后回复

**Comment by fantastlcok** [comment]
@thundernet8 
**问题1**
wp固定连接设置：https://域名/sj/%post_id%
主题商店固定连接设置：
http://ww1.sinaimg.cn/large/ec76730dgy1fcqg2id2h2j20fz07ngm1.jpg

访问商店首页404，访问商店分类、商品页面、商品tags正常。这个问题在上一版主题也存在。
如果我wp固定链接设置为 https://域名/2017/02/15/sample-post/ 则不存在此问题。

**问题3**
我是使用的账户个人页面二维码，安卓扫码后点击转账正常。IOS扫码后点击转账没有备注选项，除非手动输入转账用户。
http://ww1.sinaimg.cn/large/ec76730dgy1fcqg4pu8d6j20hr0vktau.jpg

**问题4**
我使用js打印出来的cookie无法正常登录支付宝，查了下发现有些cookie根据服务端设置js是无法读取的。手动复制header头里的cookie正常登录。

**问题5**
已去除http资源，不过这个问题问题不大，已经解决了问题。
可能是我的网站有点特别，服务器上网站确实部署的是http 80端口，但是通过CDN达到https 443的效果。

**Comment by jangrui** [comment]
### 建议：
文章页面meta信息栏望添加编辑按钮
![20170215130315](https://cloud.githubusercontent.com/assets/5895682/22961233/761eb988-f37f-11e6-81ed-164322cf764f.png)

**Comment by thundernet8** [comment]
@fantastlcok 
问题1：你的商店首页是不是应该是 域名/sj/shop

**Comment by thundernet8** [comment]
@jangrui 

可以添加，同时应该只对有编辑权限的用户可见

**Comment by fantastlcok** [comment]
@thundernet8  还真是,但是我把主题商店改成sj/shop后商品又404了

**Comment by thundernet8** [comment]
@fantastlcok 

不能改，改了之后又变成sj/sj/shop了

**Comment by jangrui** [comment]
@thundernet8 
嗯 已照做
问题：微博登陆暂时没上线吗？

**Comment by thundernet8** [comment]
@jangrui 
没有申请到微博登录接口，未测试

**Comment by thundernet8** [comment]
@fantastlcok 
你的网站固定链接特殊，添加了额外字符

我的商品首页链接获取方法里面是 域名+‘/’+shop，shop字符可自定义，但是你的固定链接应该就要改获取方法了

**Comment by fantastlcok** [comment]
@thundernet8 
不懂wp的函数，我坐等更新好了。

**Comment by jangrui** [comment]
试了一下，好着呢，最新版2.0.4
![20170215140812](https://cloud.githubusercontent.com/assets/5895682/22962558/75b91a5c-f388-11e6-9024-93617fcf4794.png)
![20170215140840](https://cloud.githubusercontent.com/assets/5895682/22962560/75bba38a-f388-11e6-8121-ca32b621c947.png)
![20170215140900](https://cloud.githubusercontent.com/assets/5895682/22962559/75ba5b38-f388-11e6-86bc-d606bcfdc041.png)

**Comment by jangrui** [comment]
@fantastlcok 
用的nginx？nginx rewrite规则没有配置吧？

**Comment by thundernet8** [comment]
@jangrui 
他是固定链接比较特别的

**Comment by thundernet8** [comment]
有问题新开issue
