### ISSUE TITLE
[BUG]购物车支付问题 

### ISSUE THREAD

**Issue by fantastlcok** [thundernet8/Tint-Pro#23]
将商品加入购物车后生成的订单有一个子订单，就算主订单支付完成，子订单也显示未支付。
有些用户看着一个未支付不顺眼，直接将子订单删除。导致无法查看付费内容。

**Comment by thundernet8** [comment]
子订单的订单状态页面展示已经是根据父级订单计算的了

**Comment by fantastlcok** [comment]
@thundernet8 在订单管理页面，子订单是可以删除的。直接把购物车功能隐藏了。

**Comment by thundernet8** [comment]
@fantastlcok 
已经处理
