### ISSUE TITLE
站内信 未读标记

### ISSUE THREAD

**Issue by fantastlcok** [thundernet8/Tint-Pro#7]
http://ww1.sinaimg.cn/large/ec76730dgy1fcrb4btv61j20f309naan.jpg

怎么才算已读？
主题版本：2.0.4-Pro 环境：php7.1 已关闭memcahed缓存 主题缓存，已清理主题缓存。

------
已解决，原来需要自己点击用户名进入对话，然后点击 标记为已读......

**Comment by thundernet8** [comment]
点发信人进入对话，然后标记消息已读

发自我的 iPhone
