### ISSUE TITLE
2.0.4版本未合并 库存剩余代码

### ISSUE THREAD

**Issue by fantastlcok** [thundernet8/Tint-Pro#8]
如题

`
                            <div class="product_meta">
                                <span class="sku_wrapper"><?php _e('SKU: ', 'tt'); ?><span class="sku" itemprop="sku"><?php echo $productdata->ID; ?></span></span>
                                <span class="posted_in"><?php _e('Categories: ', 'tt'); ?><?php echo implode(', ', $cat_breads); ?></span>
                            </div>`
然后2.0.4更新未修改style.css内主题版本号，导致wp依旧显示2.0.3 。

**Comment by thundernet8** [comment]
是没有，你看我改动提交在发布2.0.4的提交之后

发自我的 iPhone

**Comment by fantastlcok** [comment]
@thundernet8 不好意思，我也发现了这个问题，我看标题是 2.0.4的更新内容  还以为里面提到的都有合并。
